### PR TITLE
Use single AssetLoader, agnosticize path separator

### LINKED ISSUE #22: Windows: use of double backslash in payload's path results in 404
Hi,
On my Windows computer, when the application tries to perform any operation it is always met with a 404 error because the payload looks like this` {"asset":{"key":"assets\ \image.jpg"}}` (added space Github trying to escape it) which is not acceptable. it has to be a single foward slash {"asset":{"key":"assets/image.jpg"}} . Is this an issue with just my computer or Windows in general?

### PR DESCRIPTION
**Pull request by csaunders**
This should resolve the issue with paths being all goofed
up on Windows. It also fixes some issues relating to asset
loading that was inconsistent.

Fixes #22

FYI @wolverex

### CODE REVIEW

**Comment by csaunders** [comment]
I'll need to test a build on Windows (did this work on my Mac) before I'm confident enough to merge it.

**Comment by wolverex** [comment]
hi, thanks for the fix.
I'd like to check out this branch but I am having trouble compiling go in Windows, never done it before. When I use your makefile i run into 
# phoenix-0.0.5/cmd/theme-watch
cmd\theme-watch\main.go:40: undefined: phoenix.NewEventFilterFromFilesCSV
make: *** [deps] Error 2
sorry I could not test it

**Comment by csaunders** [comment]
My makefiles are pretty terrible. I basically built them to make building distributions easier. It would be awesome to see them cross-platform compatible in the future.

Here's a build of this branch that you can try for windows. You're probably on 64-bit but the 32-bit version should run fine enough for testing this out.

MD5: a5dfa53859f2d39dba565f2f51d30bdc
Download Link: https://csaunders-opensource-builds.s3.amazonaws.com/phoenix/windows-386-2590762174.zip

**Comment by wolverex** [comment]
thanks a lot ! that's much appreciated. however it appears that the permissions for public access has not been set on that file, i'll be glad to test it afterwards

**Comment by csaunders** [comment]
every. time.

Should be good now.

**Comment by csaunders** [comment]
Verified to be working on Windows. You'll be able to grab the nightly with this patch in 10 minutes or something.

**Pull request merged**
